site_name: Notas
repo_url: https://github.com/ebteles/notas
repo_name: ebteles/notas
edit_uri: tree/master/docs

theme:
  name: material
  language: pt-BR
  logo: assets/notas_001.png
  favicon: assets/notas_001.png

markdown_extensions: 
  - attr_list

extra_css:
  - stylesheets/extra.css